### ISSUE TITLE
ECOS "pip install ecos" not working. No module named numpy

### ISSUE THREAD

**Issue by Busteren** [embotech/ecos#168]
When I try to run `pip install ecos` I get the following error:
```
(env) thor-mbp:portfolio_optimisation thor$ pip install ecos
Collecting ecos
  Using cached https://files.pythonhosted.org/packages/b6/b4/988b15513b13e8ea2eac65e97d84221ac515a735a93f046e2a2a3d7863fc/ecos-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4p/mc6q42vj40sb44pghz3w7b500000gn/T/pip-install-u9yf7bdz/ecos/setup.py", line 10, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4p/mc6q42vj40sb44pghz3w7b500000gn/T/pip-install-u9yf7bdz/ecos/
```

Seems to be fine when I install numpy first then, ecos. However, this breaks if I have a requirements file. 

OS: High Sierra (10.13.6)
Python: 3.6.6
Pip version: 18.1

**Comment by Busteren** [comment]
Moving issue to the Python-Interface, as it is directly related to that.
